¡|Dvenv/lib64/python3.6/site-packages/oauthlib/oauth1/rfc5849/errors.py 2pyXPh